version: "3.9"
services:
  keycloak:
    image: frcalderon/keycloak:1.0.0
    ports:
      - "9090:8080"
    volumes:
      - conf:/keycloak/conf
      - db:/keycloak/data/h2
    networks:
      demo:
        aliases:
          - "keycloak"
    
networks:
  demo:
    driver: bridge