version: "3.9"
services:
  keycloak:
    image: frcalderon/keycloak:1.0.0
    container_name: keycloak
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - ./conf:/keycloak/conf
      - ./db:/keycloak/data/h2
    networks:
      demo:
        aliases:
          - "keycloak"
    healthcheck:
      test: curl --fail http://host.docker.internal:8081/realms/demo || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  config-server:
    image: frcalderon/config-server:1.0.0
    container_name: config-server
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/frcalderon/config-properties.git
      - DISCOVERY_SERVER_URL=http://host.docker.internal:8761/eureka
    networks:
      demo:
        aliases:
          - "config-server"
  discovery-server:
    image: frcalderon/discovery-server:1.0.0
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=development
    networks:
      demo:
        aliases:
          - "discovery-server"
    depends_on:
      - config-server
  api-gateway:
    image: frcalderon/api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - CONFIG_SERVER_URL=http://host.docker.internal:8888
      - DISCOVERY_SERVER_URL=http://host.docker.internal:8761/eureka

    networks:
      demo:
        aliases:
          - "api-gateway"
    depends_on:
      - keycloak
      - config-server
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./mariadb_database:/var/lib/mysql
    networks:
      demo:
        aliases:
          - "mariadb"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    networks:
      demo:
        aliases:
          - "phpmyadmin"
    depends_on:
      - mariadb
  demo:
    image: frcalderon/demo-microservice:1.0.0
    container_name: demo-microservice
    ports:
      - "9001:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - CONFIG_SERVER_URL=http://host.docker.internal:8888
      - DISCOVERY_SERVER_URL=http://host.docker.internal:8761/eureka
      - KEYCLOAK_REALM_URL=http://host.docker.internal:8081/realms/demo
    networks:
      demo:
        aliases:
          - "demo"
    depends_on:
      - config-server
networks:
  demo:
    name: demo-network
    driver: bridge
    ipam:
      driver: default