apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: k8-config-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-config-server
  labels:
    app: k8-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-config-server
  template:
    metadata:
      labels:
        app: k8-config-server
    spec:
      containers:
        - name: config-server
          image: frcalderon/config-server:1.0.0
          imagePullPolicy: Always
          env:
            - name: DISCOVERY_SERVER_URL
              value: http://discovery-server:8761/eureka
            - name: CONFIG_REPOSITORY_URL
              value: https://github.com/frcalderon/config-properties.git