apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
    - port: 9001
      targetPort: 8080
  selector:
    app: k8-demo-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-demo-service
  labels:
    app: k8-demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-demo-service
  template:
    metadata:
      labels:
        app: k8-demo-service
    spec:
      containers:
        - name: demo-service
          image: frcalderon/demo-microservice:1.0.0
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: development
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: DISCOVERY_SERVER_URL
              value: http://discovery-server:8761/eureka
            - name: KEYCLOAK_REALM_URL
              value: http://keycloak:8081/realms/demo