apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: k8-discovery-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-discovery-server
  labels:
    app: k8-discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-discovery-server
  template:
    metadata:
      labels:
        app: k8-discovery-server
    spec:
      containers:
        - name: discovery-server
          image: frcalderon/discovery-server:1.0.0
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
      hostAliases:
        - ip: 192.168.49.2
          hostnames:
            - kube