apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: k8-keycloak

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-conf
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/docker/conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-conf
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/docker/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-keycloak
  labels:
    app: k8-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-keycloak
  template:
    metadata:
      labels:
        app: k8-keycloak
    spec:
      containers:
        - name: keycloak
          image: frcalderon/keycloak:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/keycloak/conf"
              name: conf-pv-storage
            - mountPath: "/keycloak/data/h2"
              name: db-pv-storage
      volumes:
        - name: conf-pv-storage
          persistentVolumeClaim:
            claimName: pv-claim-conf
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: pv-claim-db
